---
title: "flex_dashboard_test"
author: "G. Conway"
knit: (function(inputFile, encoding) {
      out_dir <- 'docs';
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_file=file.path(dirname(inputFile), out_dir, 'index.html')) })
output:
  flexdashboard::flex_dashboard:
    orientation: column
    vertical_layout: fill
    theme: yeti
---

HOME
=======================================================================

***This is the home page for this test case with flexdashboards.***

Petal Width {data-navmenu="Plots"}
=======================================================================


### Petal Width Count by Species
```{r}
data("iris")

library(tidyverse)
library(plotly)

ggplotly(ggplot(iris, aes(Petal.Width, color = Species)) +
  geom_bar())
```

Petal Length {data-navmenu="Plots"}
=======================================================================


### Petal Length Count by Species
```{r}
ggplotly(ggplot(iris, aes(Petal.Length, color = Species)) +
  geom_bar())
```


Sample Data
=======================================================================

Column
-----------------------------------------------------------------------

### Number of samples per species

```{r}
table(iris$Species)
```


Column
-----------------------------------------------------------------------

### Showing latex formulas

$A + B = C$

<br>

$\frac{1}{C} = some value$

<br> 

$\hat{Y} = \beta_0 + \beta_1X_1 + \beta_2X_2$


### Section showing a code block
```{r, echo = T, eval = F}
a <- 2 + 2

b <- function(x){
  print(x^2)
}

b(a)

rm(a, b) # clean memory
```